### ISSUE TITLE
[BUG] After refreshing gets 404

### ISSUE THREAD

**Issue by GetoXs** [julianpoemp/ngx-htaccess-generator#1]
With Angular 8 there is an issue:
1. Type main page -> redirect to /en/desktop (fine)
2. Try F5/Refresh and gets 404

The problem do not occurs it I add
`  RewriteEngine On`
after line `<IfModule mod_rewrite.c>` 

Maybe it is because of old Apache?

**Comment by julianpoemp** [comment]
you are right, I'll fix it, thanks!
The generator is based on my gist file that I created earlier. The gist file contains the "Rewrite On" line, but I forgot to add it to the generator.
https://gist.github.com/julianpoemp/bcf277cb56d2420cc53ec630a04a3566#file-htaccess
