### ISSUE TITLE
Redirect to HTTPS does not work

### ISSUE THREAD

**Issue by Artaud** [julianpoemp/ngx-htaccess-generator#6]
Redirection to HTTPS does not work for me if I deliberately type http://.... into the address bar.
There is redirection flag [R] missing at the end of the redirecting line.
Currently is:
`RewriteRule (.*) https://%{HTTP_HOST}%{REQUEST_URI} [L]`

Should be:
`RewriteRule (.*) https://%{HTTP_HOST}%{REQUEST_URI} [R,L]`
or 
`RewriteRule (.*) https://%{HTTP_HOST}%{REQUEST_URI} [R=301,L]`

**Comment by julianpoemp** [comment]
Thanks! I fixed it. Sorry for my late response, I got no email notification when a new issue was created.
