### ISSUE TITLE
Don't redirect non-existing assets to index.html

### ISSUE THREAD

**Issue by Narretz** [julianpoemp/ngx-htaccess-generator#9]
Hi, this is a great tool.

One thing I think could be improved is to prevent asset files like js, css, jpg that **do not exist** from being redirected to index.html.

This can for example be a problem when you update your deployment, but a user has the old version open and for example navigates to a part of of the app that dynamically requires javascript. The browser will then receive index.html for the asset file which will fail, but may be also cached by the browser, so that even after a reload the user will still get a broken app.

Does that make sense?

**Comment by julianpoemp** [comment]
@Narretz it makes sense. At the moment I don't know a solution to this problem. I think I have to find a way to prevent redirection after receiving `404 HTTP Code`. But this should not affect the general redirection for angular routes...

**Comment by Narretz** [comment]
Hi  @julianpoemp the way I did it in the end was this:

```
# If the requested resource doesn't exist, use index.html but only if it's not an asset file
RewriteCond %{REQUEST_URI} !\.(css|js|jpeg)$
RewriteRule ^(.*) /index.html [NC,L]
```
This obviously assumes that the routes in your angular app never end in .css, .js .jpeg which could be tricky with clean urls I guess?
Caveat is also that I did it for a toy project and don't actually know that much about htaccess rules and possible unwanted side effect.

**Comment by julianpoemp** [comment]
@Narretz thanks. I experimented a little bit and found a solution. Can you try it, please?

Uncomment the line that contains `index.html` and add the following line:
````
# Redirect all non-file routes to index.html
RewriteRule ^(?!.*\.).*$ index.html [NC,L]
````

It worked for me.
